#!/bin/sh

INTERFACE="eth0"
SELFIP="0.0.0.0"
SSHPORT="22"

iptables -F

iptables -A INPUT -p icmp -j ACCEPT

# allow not new
iptables -A INPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT

# localhost
iptables -A INPUT -i lo -j ACCEPT

# http
iptables -A INPUT -p tcp -m tcp -i $INTERFACE --dport 80 -j ACCEPT
iptables -A INPUT -p tcp -m tcp -i $INTERFACE --dport 443 -j ACCEPT

# ssh
iptables -A INPUT -p tcp -m tcp -i $INTERFACE --dport $SSHPORT -j ACCEPT

# svn
iptables -A INPUT -p tcp -m tcp -i $INTERFACE -s $SELFIP/32 --dport 3690 -j ACCEPT

# block icmp
iptables -A INPUT -p tcp -j REJECT --reject-with tcp-reset
iptables -A INPUT -p udp -j REJECT --reject-with icmp-port-unreachable
iptables -A INPUT -j REJECT --reject-with icmp-proto-unreachable

# block other
iptables -A INPUT -i $INTERFACE -j DROP

